dataset_name: "linemod"
cls_type: "duck"
n_total_epoch: 20
log_dir: "../../exp/ope_lm_refiner"
use_render_data: False
use_fuse_data: False
wandb:
  enable: True
  log_imgs: False
  project_name: "ope-lm-refiner"
name: "dfv2"
description: >
  Example training and evaluation for Linemod ape class